### PR TITLE
Commands Refactor

### PR DESCRIPTION
**Pull request by Samkist**
General Overview of PR
The goal of this pull request is primarily to simplify the commands code for the Eco developers, but also will add tools for the Eco end user. The PR deprecates HandledCommand and DelegatedBukkitCommand and removes them from any usage. The PR accomplishes this simplification by using delegate interfaces in PluginCommand and SubCommand. PluginCommandBase was written for this reason, I needed a way to delegate the parent specific methods to the backend. PluginCommand and SubCommand use PluginCommandBase and CommandBase as delegates respectively. 

Progress Made:
- Pull Request Complete.
- Added NotificationException
- Added notification methods for Eco end user use in commands
- Added Eco#createPluginCommand()
- Added Eco#createSubCommand()
- Added EcoDelegatedBukkitCommand.kt
- Added EcoHandledCommand.kt
- Added EcoSubCommand.kt
- Added EcoPluginCommand.kt
- Removed HandledCommand in a breaking change (they shouldn't have overridden it if they did)
- Deprecated DelegatedBukkitCommand for removal
- Added notification functions as extension functions for kotlin users

To-do
- Have Auxilor Review

Tested _(tested with multiple of my own eco plugins, not yet with any of aux's)_
- Tab Completion
- Command/SubCommand Functionality
- Notification Methods

Usage Example:
An example of a send announcement command.
```kotlin
override fun onExecute(sender: CommandSender, args: MutableList<String>) {
        val playerName = args.getOrNull(0).notifyNull("requires-player")
        val player = Bukkit.getPlayer(playerName).notifyNull("invalid-player")
        val schedulerName = args.getOrNull(1).notifyNull("scheduler-required")
        val scheduler = Schedulers.schedulers()[schedulerName].notifyNull("invalid-scheduler")
        val announcementName = args.getOrNull(2).notifyNull("announcement-required")
        val announcement = scheduler.announcementMap[announcementName].notifyNull("invalid-announcement")

        sender.sendMessage(
            plugin.langYml.getMessage("announcement-sent")
        )
        announcement.announce(player)
    }
```

Please note: To-Do may not be a complete roadmap if there is anything amiss let me know and I will fix it asap! :)

### CODE REVIEW

**Comment by WillFP** [comment]
This is great! I'll do a few refinements I'll definitely have missed after I merge it, but otherwise really top stuff!

**Comment by Samkist** [comment]
> This is great! I'll do a few refinements I'll definitely have missed after I merge it, but otherwise really top stuff!

Awesome, thx 😄

**Comment by WillFP** [comment]
This is absolutely beautiful, I've gone and merged it into develop

**Comment by WillFP** [comment]
For future so it actually shows as merged rather than closed, open PRs into develop or a new branch!

**Pull request closed without merging**
